version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - hapi-fhir-mysql
    links:
      - hapi-fhir-mysql
    env_file:
      - hapi-fhir-jpaserver-start.env
  hapi-fhir-mysql:
    image: mysql:5.7.28
    container_name: hapi-fhir-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
    env_file:
      - hapi-fhir-jpaserver-start.env
    volumes:
      - hapi-fhir-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  hapi-fhir-mysql: